title: Cybersec Blog
description: "Offensive security, Malwarw developtment and all things cybersecurity."
baseurl: ""
url: ""
future: true
permalink: /:year/:month/:title/
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:name/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock


#title: Cybersec blog
#future: true
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
 #- jekyll-remote-theme
