title: z3vxo Blog
description: "Offensive security, Malware developtment and all things cybersecurity."
baseurl: ""
url: ""
future: true
permalink: /:year/:month/:title/
markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock


#title: Cybersec blog
#future: true
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
 #- jekyll-remote-theme
